### ISSUE TITLE
Remove Dependency on OC client

### ISSUE THREAD

**Issue by GuilhermeCamposo** [GuilhermeCamposo/workshop_camel-k#2]
Currently we are login using oc as an adhoc command. We need to change that to use k8s module authentication https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html

**Comment by bit4man** [comment]
There are two ways - using k8s_auth or use KUBECONFIG env pointing to a existing key. The latter allows you to just remove the oc login, the first requires an "api_key" dict defined for each k8s task, with the result from k8s_auth:

```
    - name: authenticate
      k8s_auth:
        username: peter
        password: xxxxxxxxxxxx
      register: oauth 

    - name: Get cluster name
      k8s_info:
        api_key: "{{ oauth.k8s_auth.api_key }}"
        name: config
        namespace: openshift-kube-controller-manager
        kind: ConfigMap
      register: config
```
Note, this requires a module_defaults where the host, ca etc. are defined.
